Software-Development-Pakistan/Software-Development-Pakistan.github.io

CONTRIBUTING.md
Career Paths/README.md
Career Paths/Web Development/README.md
FAQs/README.md
Learning Resources/README.md
README.md

- Made the content concise, 
- Removed unnecessarily long content. 
- Made sure things follow a format in FAQ. 
Lets have a discussion over this PR if some change doesn't make sense @Rubix982

Improvement recommendations

---

career-paths/DevOps/index.md

Fixes few grammar mistakes
Adds new links and references
Rephrases certain parts for brevity
*open for feedback and suggestions

Updates details and Adds new information

---

FAQs/index.md

Solving issue #29 
All links for official websites of universities are added

add university website links in FAQs page

---

_layouts/base.html
_sass/imports/_header.scss
index.md

- Removed feedback section from the home page. 
- Added a fixed button on the bottom right.

Add floating feedback button

---

career-paths/index.md

Adds `comments: true` option to the template.

edit template for career-paths and set comments to true

---

career-paths/web-dev/index.md

I have made some general changes and added a few additional resources/links including people to follow and YouTube channels.

update web-dev with additional resources and links

---

FAQs/index.md
career-paths/web-dev/index.md
learning-resources/web-development/index.md

Updated web-dev learning resources section and fixed a few typos.

Update web dev learning resources

---

index.md

Removes invalid link for LinkedIn profile

Fixes broken link

---

career-paths/index.md

Fixes left-menu career path link of cloud development

Fixes cloud-dev link

---

career-paths/DevOps/index.md

Removes the duplicate technology details
Updates Getting Started section with more context

Adds details, Formats, Removes duplicates

---

career-paths/DevOps/index.md
career-paths/architect/index.md
career-paths/index.md

📜 Documentation
Enhances the `architect` career path.

Career path architect - complete PR

---

_config.yml

🏆 Enhancements
Improves the title by removing non-functional words

Removes the word "Content Repository" from title

---

blog/index.md

💔 Breaking Changes
🐛 Bug Fix
Removes page which is empty

Removes unused blog file

---

career-paths/architect/index.md

🏆 Enhancements
Adds more details in the architecture career-path

Updates more information for Architect role

---

career-paths/web-dev/index.md

🏆 Enhancements
🐛 Bug Fix
Formats the page. Adds some details.

Adds details for Software Development

---

career-paths/DevOps/index.md

🏆 Enhancements
Adds roadmap.sh link in DevOps career path

Adds Roadmap for Devops

---

career-paths/software-dev/index.md

🐛 Bug Fix
Moves testing and processes topics from DevOps to Software Engineering for relevancy

Moves topics from DevOps to SE

---

career-paths/DevOps/index.md

🏆 Enhancements
Adds a relevant learning material link in DevOps career path

Adds link in learning material

---

career-paths/DevOps/index.md

🏆 Enhancements
Adds more FAQs
📜 Documentation
Adds courses references
🐛 Bug Fix
Removes Software Engineering domain references

Adds details and removes cross domain references

---

career-paths/software-dev/index.md

🏆 Enhancements
Adds details on software developer career path.

Adds information on Career-path

---

career-paths/web-dev/index.md

🏆 Enhancements
Adds a podcast link for web development career path
🐛 Bug Fix
Removes broken link

Adds podcast link and remove broken link

---

career-paths/DevOps/index.md

🏆 Enhancements
Adds learning resources link for DevOps career path

Adds Youtube Channel link

---

career-paths/OS/index.md

🐛 Bug Fix
Fixes typos and updates some parts for brevity

Fixes some typos for brevity

---

_config.yml

🏆 Enhancements
🏠 Internal
Adds new plugins for feed and sitemap to improve site SEO

Adds feed and sitemap for better SEO

---

index.md
learning-resources/misc/index.md

🏆 Enhancements
Fixes few spelling mistakes
📜 Documentation
Adds maintainer of the website

Adds new maintainer and fixed some typos

---

Gemfile
Gemfile.lock
_config.yml

🏆 Enhancements
Adds plugin in Gemfile
🐛 Bug Fix
Updates favicon config

Updates config for favicon & Gemfile for Plugins

---

career-paths/DevOps/index.md

🏆 Enhancements
Adds a link and 1 line description in DevOps career path

Adds a relevant link

---

career-paths/engineering-manager/index.md

🏆 Enhancements
Adds new career path for Engineering Manager.

Adds new career path of engineering manager

---

netlify.toml

💔 Breaking Changes
🏠 Internal
Removes netlify config file

Removes unused netlify config

---

career-paths/index.md

💔 Breaking Changes
🏆 Enhancements
Adds EM career path
Removes OS career path

AddsEM career Path

---

learning-resources/web-development/index.md

🏆 Enhancements
Added some new resources.

add new misc. resources

---

learning-resources/misc/index.md

Adding repo heading link in Table of Contents
